#! /usr/bin/env python

from upower_ros.battery_node import BatteryNode

import rospy


if __name__ == "__main__":
    rospy.init_node("battery_node")
    battery_node = BatteryNode()
    battery_node.loop()

